language: python

sudo: required

python:
  - '3.5'

services:
  - docker

addons:
  postgresql: '9.5'

env:
  matrix:
    - SECRET_KEY="thisisverysecretandveryveryveryveryveryveryveryveryveryveryverylong",BAELOR_API_KEY="XXXXXX"
  global:
    - secure: BFrzl60hsavHiqEyPEnc5lpQDN1+TmuEYRtbqYHJWPvYiRQHkKa3fV6fP/SE5+3pqcdC4A+ENk4H3kn8ZzK0DoD7jyeWjGxzFqOTJHJUMoGQysb2oir4wmDm7tktZmoKSJ/l/OqpJ65VFLxcRo7//TTzCmTv8BaelwSnsKXYQW+1XaIwake85XYo8LJbCqxLh9P1GxNfpAbx3dkoc++PGMRlNl8dUesm2tNEyGnjKHC0QyqQ+fSQlNu9RiyhLB0aDRK705gRJ0C7Uhx0OtgM/MgAVfKyOgCwoXZztlbT6AXeU6L/JL9w2rqpZgfMGLBIMUyIw54F/x6tw+iaYwj+h8cjUp1v/c5JambPqufxW4FTnNtb4pZNrRf5GHm2z/XxJ/O//NOus2OiJfWId4OTuOTF6V2t/igy5my5wKd6IsTHTL8b8uIAmTAAkNsoR83KfEqK0yniBtuNejZfOH1cl4uWYm6VBSzduL5UEqPw7Kq6jY4vpWOHKDz0eiwZJPlG8l2iGvbkMDhV58bF9l0ntjBphiNTYsypWcorQo9YMmxbIIY28gIZ+Z+W/SnPJic6G9F5ExMLgmTLdeEpA6XLqEqFCA5ovlXrAjfdVUfpszEq5MOCBuuCqmtMPSvNinbr9gEecN9zBgYqVIMOe6NvXMa7gODEtlki+rAusy3l3kQ=
    - secure: WGCgvi9h0YfcRww6VLMej4789PtVP2yxcsMF4lFrMDQ3E6DF3IdkPtEpIjxmJxrDdWTqTXP0RCQKGJ9dUjim0OCclRVq78s3cfY+mUjQ7GBWKR3YQl4pouphzg2W9n+nfo6RHkqM5acgmcLIk9WHGhiCuHd5EyCnssTzJPup9m2VVwvgkUWp52QkOmgpc4UywJ3O9N+V9BbBq6F0jy3R0mY/2hlNsNuaMkucYK196mwbYs5TYdz/ASmzV5uJ3Wd/3gpZ+3yzsbdgiefsNqquAVDZokfWCDSseWOlXpRW3QxlZKIqCa2oyM9+z/jOsDWksO4m+fxgqX7xsRNe0BqzdRHt03IpGsk+yvGnJqDkYv97Bl3V7Tvu9XeYr/yfR+Csb+HMe3VMaldFZrQopqrspD0lvRorYW0tCEEeKqcF5lieG9YyuzEgs1xFXYseZPvsTcAUdC+kAz/Ogk/sjZ8iqfDVws2HlycSKt/A8Cy5TfhFMKfot6LFcQ4X+48P5I1nUhISTDkLt9LiYtOW3BU5AM1kr8c0DZxMMYVRkuWcei9lS+MbdaAYgISgeYuJtwj4pjPWrJMlPsCdIEv0F3ZgP/QYCS74EBs6o+Iq9J9wOn/y5ySTRmJcTgtdSm3uQ39QlsEfblVZQKAGBlMIxkxeHnc6XwxFRV0Y15y/F80xNX4=

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip wheel codecov
  - make dev

before_script:
  - createdb -E UTF-8 taytay -U postgres -O $USER

script:
  - make lint
  - make test

after_success:
  - codecov
  - docker --version
  - pip install -U awscli
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t taytay-$(git branch).
  - docker tag taytay-$(git branch):latest 122034113952.dkr.ecr.us-east-1.amazonaws.com/taytay-$(git branch):latest
  - docker push 122034113952.dkr.ecr.us-east-1.amazonaws.com/taytay-$(git branch):latest
